### PR TITLE
Support for Mavericks

### PR DESCRIPTION
**Pull request by joongimin**
Project settings for osx 10.9 SDK

Fixed bug where url subl://open/?url=file:///etc/hosts&line=2 didn't open properly

### CODE REVIEW

**Comment by kbrock** [comment]
Hello.
I'm also having trouble with subl-handler and Mavericks.

Is there anything people can do to help this get merged in?

Thanks

**Comment by barbolo** [comment]
+1 for the mavericks fix

**Comment by jamesbebbington** [comment]
Could we get a new release for this update please?

**Comment by joongimin** [comment]
@fractious Check out https://github.com/joongimin/subl-handler/releases

**Comment by jamesbebbington** [comment]
Sweet. Thanks @joongimin.

**Pull request merged**
