### PR TITLE
Convert to Sublime Text 3 and general cleanup

### PR DESCRIPTION
**Pull request by corysimmons**

### CODE REVIEW

**Comment by evgenyneu** [comment]
I would love to have it merged. It does not work with ST3 right now.

**Comment by corysimmons** [comment]
@evgenyneu I forked the ST3 version here: https://github.com/corysimmons/subl-handler

I also think there's another/better PR in this repo that let's the user pick between 2 and 3 - it should probably get reviewed/merged, but in lieu of that, feel free to use my fork - works for me. =)

**Comment by evgenyneu** [comment]
@corysimmons, thank you sir, you saved my day!

**Comment by corysimmons** [comment]
=)

**Pull request closed without merging**
